version: "3.8"
services:
  audiobook-organizer:
    image: jeffsui/audiobook-organizer:latest
    volumes:
      - /mnt/disk1/tmp:/input:ro
      - /mnt/disk1/tmp/organized:/output
    environment:
      - AO_LAYOUT=author-series-title
      - AO_VERBOSE=true
    command: rename --dir=/input --out=/output --dry-run
  bragi:
    image: ghcr.io/djdembeck/bragibooks:main
    container_name: bragibooks
    environment:
      - LOG_LEVEL=INFO
      - DEBUG=False
      - UID=1000
      - GID=1000
    volumes:
      - ./bragi/:/config
      - ./:/input
      - ./output:/output
      - ./done:/done
    ports:
      - 8040:8000
    restart: unless-stopped
